export const MENU_LOADING = 'MENU_LOADING';
export const MENU_FAILED = 'MENU_FAILED';
export const ADD_MENU = 'ADD_MENU';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';